version: '2'
services:
  influxdb:
    image: influxdb:${influxVer}
    ports:
      - '8086:8086'
      - '2003:2003'
    volumes:
      - ./influxdb/lib/:/var/lib/influxdb
      - ./influxdb/conf/:/etc/influxdb/
      
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:${grafVer}
    ports:
      - '3000:3000'
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      
volumes:
  grafana_data:
  influxdb-storage:
    external: true
