version: '3.6'
services:
  telegraf:
    image: telegraf:${telegrafVer}
    container_name: telegraf
    env_file: 
      - .env
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:${influxVer}
    container_name: influxdb
    env_file: 
      - .env
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb/lib/:/var/lib/influxdb
      - ./influxdb/conf/:/etc/influxdb/
    environment:
      - INFLUXDB_DB=jmeter
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  grafana:
    image: grafana/grafana:${grafVer}
    container_name: grafana
    depends_on:
      - influxdb
    env_file: 
      - .env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  grafana_data: {}
  influxdb_data: {}
